# Generated by Django 6.0.2 on 2026-03-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_github_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='body',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='core/images'),
        ),
    ]
