# Generated by Django 6.0.2 on 2026-03-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='projects/placeholder.png', null=True, upload_to='projects/thumbnails/'),
        ),
    ]
